### ISSUE TITLE
Internal error: instance member did not have expected internal form

### ISSUE THREAD

**Issue by jindraivanek** [fable-compiler/repl#96] opened 2019-08-27 13:29 UTC
```fs
type MyType =
    | En
    | It
    | Fr
    override this.ToString() = toString this
    static member fromString s = fromString<MyType> s
```

produce errors:
```
internal error: e.data[i] is null (Failure)
internal error: GetInstanceMemberThisVariable: instance member did not have expected internal form (Failure)
```

[link](https://fable.io/repl/#?code=C4TwDgpgBAsiAq5oF4BQUNQD5QKIDt1McBJYIjHAMQCcKoB7ANwhpoEsATaYAC3YDOAOngMAysA74A5gAoAlFGRRg4yexkr+A+gOABDYOwDGUALYQzAI1ZQAZjQZmJU6VAFL7j5+pkAeOERIAD53VCA&html=DwCwLgtgNgfAUAAiQ0BTAhgE3s3KKpjoLhgAOAtKgI4CuAlgG4C8ARAMID2AdmKrxQAqATzKpWCAMY8+vNnwAeYAPThoAbkkh0AJwDOhZrTAAzCgA5WOZMFUZsiGwCNOmYdaS2Xb+LbWwgA&css=Q)

F# compiler, Fable on desktop, and interestingly also try.fsharp.org is behaving as expected: [link](https://try.fsharp.org/#?code=C4TwDgpgBAsiAq5oF4BQUNQD5QKIDt1McBJYIjHAMQCcKoB7ANwhpoEsATaYAC3YDOAOngMAysA74A5gAoAlFGRRg4yexkr+A+gOABDYOwDGUALYQzAI1ZQAZjQZmJU6VAFL7j5+pkAeOERIAD53IA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q)

**Comment by alfonsogarciacaro** [comment] 2019-08-27 17:13
Hi @jindraivanek! Thanks for the report. The error is indeed weird but could you please put the whole compilable code (with the missing `toString` and `fromString` methods)? Right now is difficult to isolate the problem because when I comment one of the two last lines I get other errors.

**Comment by jindraivanek** [comment] 2019-08-28 07:23
Hi @alfonsogarciacaro! I did some more digging, and I minimized repro to:
```
type T() =
  member __.M = foo
```

`T` can be also union or record.

* by defining `foo` (making code compilable) error disappear
* if part of bigger file, all code from start of type is highlighted as error [link](https://fable.io/repl/#?code=LYewJgrgNgpgBAZQmEBrCAoDIAOMB2iAngM4AuMwAdAMIhSwDGZAliPiVQOIEwBOLRtjyEAYgEMARrCoAlGOObCCcCdJhyFzKgAU+uEssIBRKMBYkAFkbinzVzYrJYyRPHAAqACgCUcALwYcHDAlJL8cAD6kVQAsgFwAGYgIBiu7gBCIAAeCSz4zunwSCjoCVm54nx84kRwVTVEWBiwZHD6AO4keWAtMG2M9N1eJMhoEABcJeN+gcHBo6WY83AAPgB8cACC1bVUwOI4LHBeiRCE4u0gHXAAtJuda5s7jfuHx6fncJJwjDAMd02i3GVAA2pIALpg8QQnw+LCtOAAc36FQAkvgwDBcoNzm1HoMoAEgsFEYR-FcOgB6XEFElwRHABKEmkgPH0wgAKl+bIKcAA1CEEf1vjkYMNgegpmN0LN6QyRUSKZKIE9trsiFRYPgkWRrCtEWAEokoCBxG0iRtiORKHFzZYqAgAI58NpW-LOA2KixtCn4GA3AAyPoAPJF1r55ck+PU4Pk4AAGKhau5wACMcBQ8oNPqoWzAYC8-qDofDvnhUZAMcu8aTVC8RNu6b8WZWK2j3zjhDrDdTaZbqTbQ4ZudBKLI6Mx2MzscheYLIxlEGhUPBsKwOfI2bVCBgTreOEQe6oZBAL1qwrap+mZVyE0QS+JK2y8qtu-3B0P75PZ41r8236nueTR9G04gMAAqvgLBOhA8D4BAwDhHw3RzPMiIkCKfoBnAAAS4hWLuZBhhG8IrAhSH8IYKxvseiQsFAFAxl4XghusfgJmR8y0fu0bgUSmFkPOvSgXAJD0AAblIsBiY+aHBJ03Qqv+R77ocIhGl4hJKUuXHBDxVDqQQmmSGKOlLHpO50VW-H1JB0GwTAl7tDAOBQIoMBbGQOggMM2TShZlI8kSxYAGrgXBcABeMT7zKCqxJFWsa1smXjAVqBC6pYcC5E2-aAtuwTxYlMY-Cl9bpdqWU5X2fj3IVbYsIksYUo8ABkbWdhShJwHqKhhRF8D-JhOUrmCkJrBCk3OXwMCMLJkjkCwZAQBQQU9V4-k3hAcpemBAA0PwUk1wVwOsFKVZleo1X1hCdPyab7QmcDDfAnT7YS8onZc53qq8VXXbkt1iXucAAN5wEQLD-EauQAL4vVAmFfc12RjWuCTPbdDWgmmyaXTqgMQg1NEAcen4nLNbkeV5PndJU3yWcOVm8QxTFiZJ0lOczpOqVQhJMG0i6LawK1rZcXiSA9cLZq9C1LWL8AS1L+UvqJ46iCwKFkAg9CrWw5Ly6Lq3wM9z3rGT+6WAoImIjgEAAF4OzJ8lwKCoIJgA3Im3sABze3AADM3tez7wQAGwhyHxNth7UdwAALAHocp8n3tptH2agpHcAAOzx2H-th2HKfE1nocZ3AOeJ97wfF6niYxyscclwH+dwAAnAXocAEyZ7Hodd-X8ehzXYdpmXA8jwHQ+V6PDcAKxN3FDd12HC-d-HPfL0Vocb8PrfBKH7cJxCO9WteS7Ofky2+Ak9tO7ALhuPAsTgP8CTbc-7ixCQSLEgleQgkMAJV1lACSTlRIQBwGAc08AvDAD-hMX+SI-AIPflAZBGDdrzAOGQRg2VEH-w6MtfU3E4BAJFPcOAD9nbc3IWAiBgJkT9E1trMB+t2AhAwc5MgXNZDXByqhXqMZQRTVBCVGq8ZsjdGoWQI0Yi3bZCmmXUSEloY3HQViTBb9tEtgsDgc0BDYrBDACwCS24xGWMzOYkmbs4A0HciQboAAiRg4FGAuLgDvIcEi+HqDdj4nmRVJGPHjKAbRBVgnBP8bAARNxQR2OifMDshB4yPHqskrJ8wzESXsY4girizFImWl48RSTsnDnIMxE6hssbW0IC4rxctqn5H-vgPwKjvF2KCcESQojek2IscEiRBTnFwDcewMg+gkZlLsRI3JFSQljNcbgW4khVqnnwC4pZ8wADy+BHGCFQCcM4hBIjMLMSQQx+DsqULIJ03ZEjqkTPuXM5JizsmjKcasnA6zNnsB2ZUuAByjmMBOZ8c5lyDFGOyowmAjyvliWmRM+FZSz5YCpFSbYOAcAYD0CAJENRqDAFQAgFgwA3LwBvm0aBsC1rqIDCAzYBKiXiGoCQvU8gnAICIPgAh+h8Bslcf8ewlhbjqR2VaVlxKqB8HOBgIAA&html=DwCwLgtgNgfAUKApgQwCbwAQeBRZkbhgAOAtIgI4CuAlgG4C8A5AMID2AdmIl6QCoBPYoiYYAxp25dm3AB5gA9OGgBucSGQAnAM54GVMADNSADiaZs2sZprEwGbZrEMARAH03ACQDyAZT4eClA0AEbaCpooYmAAdMSabKhU0TScMRA0HDEAVtouMMAKVjZ2FsDFtvaOzu5efgFuQaHhkcjRpKhsEHEJSSlpGVm5+YUVpQhKKOgIIYkC4lDI2tquyMRkElzImYia+XBYWMCo9Bg0qK6IUBnaIKRrxC4LSysuVzd3DyMKJ3TwhbNUAJ-kpILAgA&css=HQEwlg5mAuAEDeAoWLYAsCmk3QFywCYAGABwA8BuZVEgQxHADsJ8BGAVnKtVmgzOgBaWgBtIjfAGMMjPgCduqALa05UCbE6VqKAG4Y50MJNHCxEDUrAMRGRSgBGtSQGsIcgPYBXRiEGSPEQ85fHMcdwwZe1gAd2toNHwCLWiAMw9ZQQBnMAAvDCSAFi4dWDFGDEFMbDxCUm0eBw8ybLR6Dxj8IlhugGZyWAcRZxcqAF9ERFBIGFwMJRJoAE8EUqdXd29ff0Dg0Jr3WiXxyeATEUlVnjiQBPwANl766Ka5EAMkgazA60Hh1xewXeckEcnoYC8WTYKVKdAYYGYbGeiAmUw8JEEDi80GgGSuqGqEBw+EKyJ4cKYLFgHGifAEZnEUhk8miKjUCPw7Gi+kMxlMokZsCsNjsaxGmx8fgCQRCZRqQy8ouu8USmhhPHSmRy+SKJR45UqhOJsFJetQki8cm+spIHgRLLWzVa7U6PTd-TIfxGJymAVknhEWXxKHAWRIwyW+FStgaqBud1gjzJqAAVpCjKkljtZMymTmFCjEEA)

And now really strange thing: if I changed `foo` to `x` it works, moreover pattern what names make it bomb is quite unclear

produce internal error:
* foo
* strange
* toString
* aoo
* boo
* coo
* loo
* noo
* ooo (but oo and oooo works!)
* poo
* soo
* aaa
* nnn
* rrr

not produce internal error:
* x
* xxx
* xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
* realllylongnamerealllylongnamerealllylongnamerealllylongname
* fo
* any `[a-z]oo` not mentioned above 
* any triple of same char not mentioned above

WAT? 😲

Only pattern that seems to hold is that any 1 or 2 character name works.

 Now I am really curious what could produce this strange behavior. :)

**Comment by alfonsogarciacaro** [comment] 2019-08-28 09:29
Hmm, interesting. Thanks a lot for investigating the issue @jindraivanek! Now I'm curious to know what causes this behavior too :wink: @ncave Does this ring any bell?

**Comment by alfonsogarciacaro** [comment] 2019-08-29 13:20
Wow, it's incredible that you could pinpoint such a weird issue so quickly @ncave! Thanks to your detailed information I could easily [add a fix to Fable](https://github.com/fable-compiler/Fable/commit/9db82416dcb16031bf4258b0768e2494a1ba406b) (hopefully that's the right one). I'll publish a new version of the REPL to see if it's solved. Thank you!

**Comment by ncave** [comment] 2019-08-29 14:36
@alfonsogarciacaro Without testing your solution (which I'm sure works for `KeyValuePair`), is it possible to make it apply to all struct (Value types) (not just `KeyValuePair`)? Cause they all have the same issue.

**Comment by alfonsogarciacaro** [comment] 2019-08-29 16:14
I need to check. I guess we could call the constructor without arguments but I'm not sure if the fields would be initialized properly (for example, int fields to 0).

I'll move this issue to Fable repo so I don't forget :+1:

**Comment by jindraivanek** [comment] 2019-08-30 07:19
Thanks @ncave for great explanation!

**Comment by alfonsogarciacaro** [comment] 2019-09-02 17:04
The issue is fixed now in the REPL (please remember to clear the browser cache if you still see it). Than you both!

**Closed** 2019-09-02 17:09 UTC
