### ISSUE TITLE
REPL broken?

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/repl#80] opened 2018-11-19 21:04 UTC
I've gotten the following error in the REPL today (https://fable.io/repl), with no rendered output:

Chrome: `Uncaught SyntaxError: The requested module '../../fable-core/Types.js' does not provide an export named 'L'`

Firefox: `SyntaxError: import not found: L`

**Comment by MangelMaxime** [comment] 2018-11-19 21:13
I can confirm.

@alfonsogarciacaro I think the latest release broke the repl. We really need to test it before publishing or to add automatic tests :)

**Comment by alfonsogarciacaro** [comment] 2018-11-19 22:16
Ah, damn. This is because the Repl.Lib files were built with a previous version of Fable 😬 We should build the Repl.Lib together with the Repl bundle to avoid these version mismatches.

For now, the online repl should be fixed now, thanks for reporting!

**Closed by alfonsogarciacaro** 2018-11-19 22:16 UTC
