### ISSUE TITLE
Unable to scroll using scrollwheel in F# code (using Fx 69)

### ISSUE THREAD

**Issue by darklajid** [fable-compiler/repl#91] opened 2019-05-21 08:26 UTC
This might be entirely me, running Firefox 69 - but maybe it's something you're interested in anyway: 

- Navigate to https://fable.io/repl/
- Load a sample (say the Thoth RandomUser one)
- Try scrolling in the F# code or the generated JS code using the mouse wheel

For me nothing happens, while navigating using the keyboard (cursor keys, home/end keys) or using the scrollbars works fine.

**Comment by MangelMaxime** [comment] 2019-05-21 08:50
Using Firefox 66

I can't scroll either in any of the editors.

However, I am able to scroll in the **Console** and **Problems** views.

**Comment by alfonsogarciacaro** [comment] 2019-05-21 08:59
Unfortunately Firefox doesn't seem to like the Fable REPL very much as it runs quite slow on it. We're not sure what the problem is as, at least on macOS, it runs reasonably fast in Chrome and Safari (it likely has to be with modern JS syntax not being optimized in FF). This makes the overall experience in FF not very pleasant whether you're able to scroll with the mouse wheel or not :/

**Comment by darklajid** [comment] 2019-05-21 09:06
> Unfortunately Firefox doesn't seem to like the Fable REPL very much as it runs quite slow on it. 

I don't know if you guys have any way of fixing that, but I do think that's secondary no? A different issue?

I stumbled upon this REPL due to a tweet and really just wanted to browse some examples / check out what Fable does and can do. Not being able to scroll _naturally_ is making this rather hard (I want to scroll on both left and right to see input / output - for me that's the reason to look at a "web playground".

There's already a popup in the bottom right, saying that one should use Safari (wrong platform) or Chrome for better performance.

**Comment by MangelMaxime** [comment] 2019-05-21 09:12
The scrolling problem is just a bug we discover thanks to your issue. The bug is actually coming from monaco itself: https://github.com/microsoft/monaco-editor/issues/1353

We just need now to see:
- if the bug will be fixed in Monaco
- Should we downgrade the Monaco version to a working version
- Is their a polyfill that we could add as a temporary fix

**Closed** 2020-02-20 10:58 UTC
Labels: bug
