### ISSUE TITLE
Autocomplete pushing the toolbar out

### ISSUE THREAD

**Issue by ncave** [fable-compiler/repl#44] opened 2018-09-26 15:13 UTC
Triggering the auto-complete menu at the end of a line is pushing the left toolbar out (hiding it completely).
The only way to get it back is to switch panes.

**Comment by MangelMaxime** [comment] 2018-09-26 16:44
I am not sure to understand.

![2018-09-26 18 41 18](https://user-images.githubusercontent.com/4760796/46095035-d87e4880-c1bb-11e8-8cd5-bfe0101aab18.gif)

Can you please try to make a gif ?

And yes I had some problem coming from the scrollable panel. Where the whole `html` element was moving of 42px to the left. This si the reason why `warning` in the problems panel are not truncated :)

I just had some idea on how to fix it. So I am putting them here so I don't forget.

1. Position the sidebar using a fixed position
2. Apply a padding/margin of 42px to the whole `body` and see if this reproduce the problem.

**Comment by ncave** [comment] 2018-09-26 17:16
@MangelMaxime I can't reliably reproduce it every time in Chrome, but here is another one (probably related) that is reproducible in Firefox:
- clear all text in editor
- press control-space to open auto-complete, press enter
- the whole pane will move vertically

**Comment by alfonsogarciacaro** [comment] 2018-10-03 23:08
Yes, I've seen this too but not sure how to reproduce either. It's mildly annoying ;)

**Comment by alfonsogarciacaro** [comment] 2018-11-09 07:17
It was actually the problems panel what made the left bar hide. It should have been fixed in 405f3cd62208bcb6a1ae9b6690439b3d4973b6ba.

**Closed by alfonsogarciacaro** 2018-11-09 07:17 UTC
